#!/bin/bash

set -e
set -u

CCOPTS="-Wall -Wextra -Werror"

SRCFILE="firmware.c"
ELFFILE="`basename "$SRCFILE" .c`.elf"

avr-gcc $CCOPTS -std=c11 -Os -g -mmcu=atmega328p -o "$ELFFILE" "$SRCFILE"
avrdude -p atmega328p -c arduino -b 57600 -P /dev/ttyUSB0 -U "$ELFFILE"

